server:
  host: 0.0.0.0
  port: 3000
  cors:
    - "http://0.0.0.0:4200"
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swagger:
  title: Site de covoiturage pour le module NWT
  description: API Covoiturage des trajets et utilisateurs
  version: 1.0
  tag: covoiturage
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/covoiturage
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
